### ISSUE TITLE
Documentación muy escueta

### ISSUE THREAD

**Issue by jcarpio** [Joseram0n/ARBOL-SIMULATOR#3]
Debéis añadir alguna información más en la documentación de cómo habéis desarrollado el proyecto, dificultades que habéis encontrado, formas de solucionarlas, descripción del menú, etc.

**Comment by Joseram0n** [comment]
¿Has echado un vistazo al sección de la wiki del proyecto? , esta practicamente todo explicado allí.

**Comment by jcarpio** [comment]
Ok, no me acordaba que estaba en la pestaña Wiki. No estaría mal que en el fichero README.md pusieseis una frase al principio indicando donde se puede encontrar la documentación. Normalmente se espera que lo necesario para entender o compilar esté en el fichero README.
